### ISSUE TITLE
Add optional .png tracker instead of .js tracker for blockers

### ISSUE THREAD

**Issue by Semperverus** [sheshbabu/freshlytics#12]
One of the first things I noticed when visiting my website after putting the freshlytics script in the page is that uBlock:Origin immediately blocked it (which I disabled shortly after for my site).

Because of this, I was wondering if it would be possible for freshlytics to "generate" a 1px by 1px invisible png file with the same filename as the ID token for the script that, when loaded, counts as a pageview. I would imagine that no actual .png would exist on the hard-drive anywhere, but when a request is put in for the freshlytics server, it would just return the data required for a png and tell the client requesting it that it exists, etc. etc.

The real hat-trick would be to make it so that you can embed both in your page, but it only counts it once if either-or-both load in the same go, in case javascript is being blocked.

If this isn't feasible or is outside the scope of the project, feel free to close this issue.

**Comment by sheshbabu** [comment]
> One of the first things I noticed when visiting my website after putting the freshlytics script in the page is that uBlock:Origin immediately blocked it (which I disabled shortly after for my site).

Thanks for the feedback! 😊 I think we should balance between what website owners want and what users want. I'm one of those users who would opt-out of product tracking even if I'm told it was collected anonymously 😅

However I don't want to be prescriptive. I think a better design would be to give the website owners a choice whether to use normal HTTP calls or to use 1px beacon images. I'm actually surprised ad blockers haven't blocked this yet 🤷‍♀️

> If this isn't feasible or is outside the scope of the project, feel free to close this issue.

Let's keep this issue open and let others chime in with their opinions 😊
