### ISSUE TITLE
Add automated security vulnerability scanner

### ISSUE THREAD

**Issue by omrprks** [sheshbabu/freshlytics#15]
Hey there,

Would be nice/good to have an automated vulnerability scanner to find any issues with npm packages, etc.

I'm partial to using Snyk (which is free for open-source projects and is available on the Github Marketplace), but if you're used to or more comfortable with any others (like Dependabot) that would be cool too!

**Comment by sheshbabu** [comment]
I assumed dependabot was enabled in all GitHub repos, didn't know this wasn't the case. 

I've enabled Snyk as per your suggestion. Thanks for raising this! 👍
