### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [sheshbabu/freshlytics#29]
Hiya,

Since your project is well thought out in terms of privacy, perhaps we could work together to remove Google Analytics from the documentation?

Hey, we could use Freshlytics. 😉

**Comment by sheshbabu** [comment]
Hi @resynth1943, which documentation are you referring to? 🙂

**Comment by resynth1943** [comment]
The one on Gitbook. freshlytics.gitbook.io, if I remember correctly.

**Comment by sheshbabu** [comment]
@resynth1943 Sorry about this, I wasn't aware that Google Analytics was being loaded in the documentation site:

<img width="1440" alt="Screenshot 2020-08-16 at 9 32 33 AM" src="https://user-images.githubusercontent.com/498909/90324620-97f06980-dfa3-11ea-9768-94806c562de9.png">

I checked the settings in Gitbook and I see Google Analytics is disabled, so maybe it's Gitbook's fallback account:

<img width="1440" alt="Screenshot 2020-08-16 at 9 32 51 AM" src="https://user-images.githubusercontent.com/498909/90324631-ba828280-dfa3-11ea-9210-2342790d7c43.png">

I'm not sure if we can disable this fallback account, if not we should move to a different documentation system.

**Comment by sheshbabu** [comment]
I've removed the link to Gitbook from the main page. Since this repo contains the same documentation and as it's also linked in the readme, it should be okay. Feel free to close this issue 😊

**Comment by resynth1943** [comment]
Awesome work, my dude!

**Comment by resynth1943** [comment]
Would you consider throwing up a GitHub Pages website? Not sure if that's plausible, just an idea ;D

**Comment by sheshbabu** [comment]
@resynth1943 Yes, planning to add a nice landing page 😊

**Comment by resynth1943** [comment]
Amazing :D
