### ISSUE TITLE
Great Express model management for PostgreSQL

### ISSUE THREAD

**Issue by goodgoodwish** [sheshbabu/freshlytics#34]
Thanks for the great example to help me learning pg + express.
Where could I contact you to ask more questions in future?  Such as email, twitter ...etc.

For now, I'd just put my question here.   ^_^

It seems you only use a small part of node-pg-migrate to run SQL file:
`"migrate": "node-pg-migrate -m ./src/server/migrations -j sql up",`

for `-j sql` , from document, https://salsita.github.io/node-pg-migrate/#/cli?id=configuration
`migration-file-language (j) - Language of the migration file to create (js or ts)`
it only support js or ts, not SQL. 

Could I write a simple function run all SQL files in migrations folder order by SQL file name timestamp(s) ?

Fyi, 
I got here from this reddit link: https://www.reddit.com/r/node/comments/da3stw/sequelize_vs_nodepostgres_nodepgmigration/f1vgy65/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by sheshbabu** [comment]
Hi @goodgoodwish,

Thanks for the kind words, hope the repo was useful!

> Could I write a simple function run all SQL files in migrations folder order by SQL file name timestamp(s) ?

Yes, it's definitely possible to do this. Store the migrations file inside a folder numbered by versions or timestamps, everytime you run the migration keep track of the latest version in a separate table in your database (commonly named as "schema_migrations") and the next time you run the migration, run the ones that come after the last run migration. Also run the migrations inside a transaction so you can rollback if there's an issue.

Thanks,
Shesh

**Comment by goodgoodwish** [comment]
Wonderful!  Thanks.
