### ISSUE TITLE
Add support for unit testing - jest

### ISSUE THREAD

**Issue by sheshbabu** [sheshbabu/freshlytics#5]

**Comment by gibsonhan** [comment]
Hey @sheshbabu , I'd like to help with adding unit testing

**Comment by sheshbabu** [comment]
@gibsonhan Awesome, thanks for the interest! 👍

Can you create a PR with jest config for both client and server sections and 1-2 example unit tests - maybe NavBar.tsx in client [1] and DateTimeUtil.ts in server [2].

Let me know if you prefer to approach this in a different way 😊

[1] https://github.com/sheshbabu/freshlytics/blob/master/src/client/components/Navbar.tsx
[2] https://github.com/sheshbabu/freshlytics/blob/master/src/server/utils/DateTimeUtil.ts

**Comment by gibsonhan** [comment]
I am new to docker. I managed to get the build running. But I am unsure what the "public url" is

**Comment by sheshbabu** [comment]
> But I am unsure what the "public url" is

It's the URL your use to access the server. If you're running in local, it'd be `http://localhost:3001`
