### ISSUE TITLE
Reduce bundle size of Semantic UI

### ISSUE THREAD

**Issue by sheshbabu** [sheshbabu/freshlytics#7]
Currently, the whole Semantic UI JS and CSS is bundled with the app. Use https://github.com/skleeschulte/babel-plugin-transform-semantic-ui-react-imports to modify the import paths so only the used JS and CSS is bundled.

This requires changes to Webpack config:
* Replace typescript loader with babel loader - https://github.com/Microsoft/TypeScript-Babel-Starter

**Comment by ivan-nikolaievskyi** [comment]
@sheshbabu Hi. Can I work on this issue?

**Comment by sheshbabu** [comment]
@ivan-nikolaievskyi Yes, that would be great! Thanks! 👍

**Comment by ivan-nikolaievskyi** [comment]
@sheshbabu please check PR and comment to it. Unfortunately, I didn't succeed in reducing bundle size. I stuck with solving this issue, so just push what I have.
